# Generated by Django 3.2.13 on 2023-12-05 06:23

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0002_alter_senior_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='occupation',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('営業', '営業'), ('医療・福祉', '医療・福祉'), ('建築・土木', '建築・土木'), ('電気・電子・機械・半導体', '電気・電子・機械・半導体'), ('コンサルタント・金融・不動産専門職', 'コンサルタント・金融・不動産専門職'), ('技能工・設備・配送・農林水産', '技能工・設備・配送・農林水産'), ('管理・事務', '管理・事務'), ('保育・教育・通訳', '保育・教育・通訳'), ('販売・フード・アミューズメント', '販売・フード・アミューズメント'), ('企画・経営', '企画・経営'), ('ITエンジニア', 'ITエンジニア'), ('医薬・食品・化学・素材', '医薬・食品・化学・素材'), ('クリエイティブ', 'クリエイティブ'), ('公共サービス', '公共サービス'), ('美容・ブライダル・ホテル・交通', '美容・ブライダル・ホテル・交通'), ('WEB・インターネット・ゲーム', 'WEB・インターネット・ゲーム')], default='選択なし', max_length=17, verbose_name='職種'),
        ),
        migrations.AddField(
            model_name='job',
            name='prefecture',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('北海道', '北海道'), ('青森県', '青森県'), ('岩手県', '岩手県'), ('宮城県', '宮城県'), ('秋田県', '秋田県'), ('山形県', '山形県'), ('福島県', '福島県'), ('茨城県', '茨城県'), ('栃木県', '栃木県'), ('群馬県', '群馬県'), ('埼玉県', '埼玉県'), ('千葉県', '千葉県'), ('東京都', '東京都'), ('神奈川県', '神奈川県'), ('新潟県', '新潟県'), ('富山県', '富山県'), ('石川県', '石川県'), ('福井県', '福井県'), ('山梨県', '山梨県'), ('長野県', '長野県'), ('岐阜県', '岐阜県'), ('静岡県', '静岡県'), ('愛知県', '愛知県'), ('三重県', '三重県'), ('滋賀県', '滋賀県'), ('京都府', '京都府'), ('大阪府', '大阪府'), ('兵庫県', '兵庫県'), ('奈良県', '奈良県'), ('和歌山県', '和歌山県'), ('鳥取県', '鳥取県'), ('島根県', '島根県'), ('岡山県', '岡山県'), ('広島県', '広島県'), ('山口県', '山口県'), ('徳島県', '徳島県'), ('香川県', '香川県'), ('愛媛県', '愛媛県'), ('高知県', '高知県'), ('福岡県', '福岡県'), ('佐賀県', '佐賀県'), ('長崎県', '長崎県'), ('熊本県', '熊本県'), ('大分県', '大分県'), ('宮崎県', '宮崎県'), ('鹿児島県', '鹿児島県'), ('沖縄県', '沖縄県')], default='選択なし', max_length=4, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('IT・通信・インターネット', 'IT・通信・インターネット'), ('商社', '商社'), ('流通・小売・フード', '流通・小売・フード'), ('金融・保険', '金融・保険'), ('不動産・建設・設備', '不動産・建設・設備'), ('環境・エネルギー', '環境・エネルギー'), ('メーカー', 'メーカー'), ('サービス・レジャー', 'サービス・レジャー'), ('マスコミ・広告・デザイン', 'マスコミ・広告・デザイン'), ('コンサルティング', 'コンサルティング'), ('運輸・交通・物流・倉庫', '運輸・交通・物流・倉庫'), ('公的機関', '公的機関')], default='選択なし', max_length=13, verbose_name='業種'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pic_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/images/company_pics')),
        ),
        migrations.AlterField(
            model_name='senior',
            name='face_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/images/senior_faces')),
        ),
    ]
