# Generated by Django 3.2.13 on 2023-12-05 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0002_alter_senior_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
