# Generated by Django 5.0 on 2023-12-05 08:33

import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0002_alter_senior_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='pic_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/images/company_pics')),
        ),
        migrations.AlterField(
            model_name='senior',
            name='face_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/images/senior_faces')),
        ),
    ]
