# Generated by Django 3.2.13 on 2023-12-06 03:30

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0003_auto_20231205_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('IT・通信・インターネット', 'IT・通信・インターネット'), ('商社', '商社'), ('流通・小売・フード', '流通・小売・フード'), ('金融・保険', '金融・保険'), ('不動産・建設・設備', '不動産・建設・設備'), ('環境・エネルギー', '環境・エネルギー'), ('メーカー', 'メーカー'), ('サービス・レジャー', 'サービス・レジャー'), ('マスコミ・広告・デザイン', 'マスコミ・広告・デザイン'), ('コンサルティング', 'コンサルティング'), ('運輸・交通・物流・倉庫', '運輸・交通・物流・倉庫'), ('公的機関', '公的機関')], default='選択なし', max_length=13, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='job',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='senior',
            name='industry',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('IT・通信・インターネット', 'IT・通信・インターネット'), ('商社', '商社'), ('流通・小売・フード', '流通・小売・フード'), ('金融・保険', '金融・保険'), ('不動産・建設・設備', '不動産・建設・設備'), ('環境・エネルギー', '環境・エネルギー'), ('メーカー', 'メーカー'), ('サービス・レジャー', 'サービス・レジャー'), ('マスコミ・広告・デザイン', 'マスコミ・広告・デザイン'), ('コンサルティング', 'コンサルティング'), ('運輸・交通・物流・倉庫', '運輸・交通・物流・倉庫'), ('公的機関', '公的機関')], default='選択なし', max_length=13, verbose_name='業種'),
        ),
        migrations.AddField(
            model_name='senior',
            name='occupation',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('営業', '営業'), ('医療・福祉', '医療・福祉'), ('建築・土木', '建築・土木'), ('電気・電子・機械・半導体', '電気・電子・機械・半導体'), ('コンサルタント・金融・不動産専門職', 'コンサルタント・金融・不動産専門職'), ('技能工・設備・配送・農林水産', '技能工・設備・配送・農林水産'), ('管理・事務', '管理・事務'), ('保育・教育・通訳', '保育・教育・通訳'), ('販売・フード・アミューズメント', '販売・フード・アミューズメント'), ('企画・経営', '企画・経営'), ('ITエンジニア', 'ITエンジニア'), ('医薬・食品・化学・素材', '医薬・食品・化学・素材'), ('クリエイティブ', 'クリエイティブ'), ('公共サービス', '公共サービス'), ('美容・ブライダル・ホテル・交通', '美容・ブライダル・ホテル・交通'), ('WEB・インターネット・ゲーム', 'WEB・インターネット・ゲーム')], default='選択なし', max_length=17, verbose_name='職種'),
        ),
        migrations.AddField(
            model_name='senior',
            name='sex',
            field=models.CharField(choices=[('選択なし', '選択なし'), ('IT・通信・インターネット', 'IT・通信・インターネット'), ('商社', '商社'), ('流通・小売・フード', '流通・小売・フード'), ('金融・保険', '金融・保険'), ('不動産・建設・設備', '不動産・建設・設備'), ('環境・エネルギー', '環境・エネルギー'), ('メーカー', 'メーカー'), ('サービス・レジャー', 'サービス・レジャー'), ('マスコミ・広告・デザイン', 'マスコミ・広告・デザイン'), ('コンサルティング', 'コンサルティング'), ('運輸・交通・物流・倉庫', '運輸・交通・物流・倉庫'), ('公的機関', '公的機関')], default='選択なし', max_length=13, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='senior',
            name='face_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/media/images/senior_pics')),
        ),
    ]
