# Generated by Django 5.0 on 2023-12-06 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0003_alter_company_pic_path_alter_senior_face_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_uid',
        ),
    ]
