# Generated by Django 3.2.13 on 2023-12-05 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0003_auto_20231205_0623'),
        ('main_func', '0004_alter_company_company_uid'),
    ]

    operations = [
    ]
