# Generated by Django 3.2.13 on 2023-12-06 04:19

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0005_merge_20231205_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='senior',
            name='face_path',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/media/images/senior_pics')),
        ),
    ]
