# Generated by Django 3.2.13 on 2023-12-06 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0004_auto_20231206_0330'),
        ('main_func', '0005_merge_20231205_1658'),
    ]

    operations = [
    ]
