# Generated by Django 3.2.13 on 2023-12-06 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0006_alter_senior_face_path'),
        ('main_func', '0006_merge_20231206_0428'),
    ]

    operations = [
    ]
