# Generated by Django 3.2.13 on 2023-12-06 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0006_merge_20231206_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.CharField(default='', max_length=20),
        ),
    ]
