# Generated by Django 3.2.13 on 2023-12-06 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_func', '0006_merge_20231206_0400'),
        ('main_func', '0006_merge_20231206_0408'),
        ('main_func', '0007_alter_job_salary'),
        ('main_func', '0007_merge_20231206_0520'),
    ]

    operations = [
    ]
